# Generated by Django 3.1.5 on 2021-11-09 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_perfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='categoria_principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.categoriastrabajo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='descripcion',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
