# Generated by Django 3.1.5 on 2021-11-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211108_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
