# Generated by Django 3.1.5 on 2021-11-13 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_ofertadeempleo_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=100)),
                ('descripcion', models.CharField(default='DESCRIPCION SIN ACTUALIZAR', max_length=500)),
                ('profesion', models.CharField(default='Profesion', max_length=100)),
                ('foto', models.ImageField(upload_to='candidatos/')),
                ('universidad_nombre', models.CharField(default='Universidad', max_length=50)),
                ('universidad_inicio', models.DateField(null=True)),
                ('universidad_fin', models.DateField(null=True)),
                ('grado', models.CharField(max_length=100)),
                ('bachiller_nombre', models.CharField(default='Preparatoria', max_length=50)),
                ('bachiller_inicio', models.DateField(null=True)),
                ('bachiller_fin', models.DateTimeField(null=True)),
                ('empleo_anterior_empresa', models.CharField(default='Empresa', max_length=50)),
                ('empleo_anterior_puesto', models.CharField(default='Puesto', max_length=50)),
                ('empleo_anterior_inicio', models.DateField(null=True)),
                ('empleo_anterior_fin', models.DateField()),
                ('empleo_anterior2_empresa', models.CharField(default='Empresa', max_length=50)),
                ('empleo_anterior2_puesto', models.CharField(default='Puesto', max_length=50)),
                ('empleo_anterior2_inicio', models.DateField(null=True)),
                ('empleo_anterior2_fin', models.DateField()),
                ('idioma_extra', models.CharField(choices=[('1', 'Inglés'), ('2', 'Chino'), ('3', 'Aleman'), ('4', 'Japones')], default='Inglés', max_length=20)),
                ('idoma_porcentaje', models.IntegerField(null=True)),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.genero')),
            ],
        ),
    ]
