# Generated by Django 3.1.5 on 2021-11-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='bachiller_fin',
            field=models.DateField(null=True),
        ),
    ]
