# Generated by Django 3.1.5 on 2021-11-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_cv_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='sexo',
            field=models.CharField(choices=[('1', 'Cualquiera'), ('2', 'Masculino'), ('3', 'Femenino')], max_length=15),
        ),
    ]
