# Generated by Django 3.1.5 on 2021-11-14 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20211113_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='nombres',
        ),
    ]
