# Generated by Django 3.1.5 on 2021-11-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20211114_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='bachiller_nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cv',
            name='descripcion',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='empleo_anterior2_puesto',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='empleo_anterior_puesto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cv',
            name='grado',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='profesion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='universidad_nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
