# Generated by Django 3.1.5 on 2021-11-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20211114_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='cv',
            name='curp',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
