# Generated by Django 3.1.5 on 2021-11-14 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20211114_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='id_usuario',
        ),
    ]
