# Generated by Django 3.1.5 on 2021-11-15 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0027_auto_20211114_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('1', 'ACEPTADO'), ('2', 'RECHAZADO'), ('3', 'EN PROCESO')], default=3, max_length=15)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ofertadeempleo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
