# Generated by Django 3.1.5 on 2021-11-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_postulante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='oferta',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='usuario',
            field=models.CharField(max_length=20),
        ),
    ]
