# Generated by Django 3.1.5 on 2021-11-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_pruebapostulante'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertadeempleo',
            name='estado',
            field=models.CharField(choices=[('1', 'ACTIVA'), ('2', 'COMPLETA')], default=1, max_length=15),
        ),
    ]
