# Generated by Django 3.1.5 on 2021-11-17 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='sexo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.genero'),
        ),
    ]
