# Generated by Django 3.1.5 on 2021-11-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20211116_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='sexo',
            field=models.CharField(choices=[('1', 'Cualquiera'), ('2', 'Masculino'), ('3', 'Femenino')], default=1, max_length=15),
        ),
    ]
