# Generated by Django 3.1.5 on 2021-11-20 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0036_auto_20211117_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertadeempleo',
            name='reclutador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
